name: 'Greetings'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'John'
outputs:
  greeting-output:
    description: "Who did we greet"
    value: ${{ steps.print_greeting.outputs.greeted_names }}
runs:
  using: "composite"
  steps:
    - name: Print Greeting
      id: print_greeting
      run: |
        echo "Hello $INPUT_WHO_TO_GREET."
        echo "greeted_names=$INPUT_WHO_TO_GREET" >> $GITHUB_OUTPUT
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
