name: exercise-5

on:
  push:
    branches:
      - master

jobs:
  custom-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Echo message
        if: github.repository == 'mats-werrebrouck/github-cicd-workshop'
        uses: ./.github/actions/greetings
        with:
          who-to-greet: 'Mats'
